name: shelfie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  geolocator: ^14.0.0
  google_maps_flutter: ^2.12.1
  path: ^1.9.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  sqflite_common_ffi_web: ^0.4.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  android: true
  
  background_image: 'assets/SplashBG.png'
  image: 'assets/Vector.png'
  branding: 'assets/Name.png'

