name: assignment2_albymb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  reactive_forms: ^17.0.1
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.0.0
  sqflite_common_ffi_web: ^0.4.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
